# -*- coding: utf-8 -*-
"""XOR NumPy Training Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cu5D5Vlw6tlVSt3vWef79TH0_Wl96aDd
"""

import numpy as np

# 1. Activation functions and their derivatives
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    # x here is already assumed to be the output of sigmoid(z)
    return x * (1 - x)

# 2. XOR Dataset (Inputs and expected Targets)
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# 3. Initialize Weights and Biases randomly
np.random.seed(42) # For reproducible results
input_nodes = 2
hidden_nodes = 3
output_nodes = 1

W1 = np.random.uniform(size=(input_nodes, hidden_nodes))
b1 = np.zeros((1, hidden_nodes))
W2 = np.random.uniform(size=(hidden_nodes, output_nodes))
b2 = np.zeros((1, output_nodes))

# 4. Hyperparameters
learning_rate = 0.5
epochs = 10000

# 5. Training Loop
for epoch in range(epochs):
    # --- FORWARD PASS ---
    hidden_layer_input = np.dot(X, W1) + b1
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, W2) + b2
    predicted_output = sigmoid(output_layer_input)

    # --- BACKPROPAGATION ---
    # Error at output layer
    error = y - predicted_output

    # Gradient/Delta at output layer (Error * direction of derivative)
    d_output = error * sigmoid_derivative(predicted_output)

    # Error at hidden layer (propagated backward through W2)
    error_hidden_layer = d_output.dot(W2.T)

    # Gradient/Delta at hidden layer
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # --- GRADIENT DESCENT (Weight Updates) ---
    W2 += hidden_layer_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate
    W1 += X.T.dot(d_hidden_layer) * learning_rate
    b1 += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    # Print progress every 2000 epochs
    if epoch % 2000 == 0:
        loss = np.mean(np.square(error)) # Mean Squared Error
        print(f"Epoch {epoch:5d} | Loss: {loss:.4f}")

# 6. Final Evaluation
print("\nFinal Trained Predictions:")
for i in range(len(X)):
    print(f"Input: {X[i]} -> Predicted: {predicted_output[i][0]:.4f} (Target: {y[i][0]})")